version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"

  mysql:
    image: mysql:5.7.25
        restart: always
        environment:
          MYSQL_DATABASE: 'tgstation'
          MYSQL_ROOT_PASSWORD: 'root'
        ports:
          - '3306:3306'
        expose:
          - '3306'